In [32]:
import pandas as pd
import numpy as np
from sklearn import linear_model 
import warnings
warnings.filterwarnings("ignore")
from sklearn import linear_model

In [33]:
#reading the csv
df_h=pd.read_csv("hiring.csv")

In [34]:
df_h

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [35]:
#checking for the shape
df_h.shape

(8, 4)

In [36]:
#checking for the statistical summary of the data
df_h.describe()

test_score(out of 10)  interview_score(out of 10)    salary($)
count               7.000000                    8.000000      8.00000
mean                7.857143                    7.875000  63000.00000
std                 1.345185                    1.642081  11501.55269
min                 6.000000                    6.000000  45000.00000
25%                 7.000000                    6.750000  57500.00000
50%                 8.000000                    7.500000  63500.00000
75%                 8.500000                    9.250000  70500.00000
max                10.000000                   10.000000  80000.00000

In [37]:
#checking for the information ir components that comprises the data
df_h.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   experience                  6 non-null      object 
 1   test_score(out of 10)       7 non-null      float64
 2   interview_score(out of 10)  8 non-null      int64  
 3   salary($)                   8 non-null      int64  
dtypes: float64(1), int64(2), object(1)
memory usage: 384.0+ bytes


In [38]:
#checking for the null values
df_h.isna().sum()

experience                    2
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [39]:
#using the median method to get the median of the test_score(out of 10)
median=df_h["test_score(out of 10)"].median()
median

8.0

In [40]:
#filling up the null value of the test_score(out of 10) column with it's meadian
df_h["test_score(out of 10)"]=df_h["test_score(out of 10)"].fillna(median)
df_h

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [41]:
from word2number import w2n

# Assuming df_h is your original DataFrame
df_new = df_h.copy()

# Dictionary to map words to numbers
word_to_num_dict = {
    'one': 1,
    'two': 2,
    'three': 3,
    'four': 4,
    'five': 5,
    'six': 6,
    'seven': 7,
    'eight': 8,
    'nine': 9,
    'ten': 10,
    'eleven': 11,
    # Add more mappings as needed
}

# Convert the "experience" column to integers using the dictionary
df_new["experience"] = df_h["experience"].map(word_to_num_dict).fillna(df_h["experience"])

# Display the new DataFrame
print(df_new)



   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    8.0                           7      72000
7        11.0                    7.0                           8      80000


In [42]:
#using the median method to get the median of the experience
median=df_new["experience"].median()
median

6.0

In [43]:
#filling up the null value of the experience column  with it's meadian
df_new["experience"]=df_new["experience"].fillna(median)
df_new

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         6.0                    8.0                           9      50000
1         6.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    8.0                           7      72000
7        11.0                    7.0                           8      80000

In [52]:
#dropping the salary column, by trying to split the dependent variable(salary) from the independent variables(experience, test_score(out of 10), interview_score(out of 10))
new_df_h =df_new.drop("salary($)",axis=1)
new_df_h

experience  test_score(out of 10)  interview_score(out of 10)
0         6.0                    8.0                           9
1         6.0                    8.0                           6
2         5.0                    6.0                           7
3         2.0                   10.0                          10
4         7.0                    9.0                           6
5         3.0                    7.0                          10
6        10.0                    8.0                           7
7        11.0                    7.0                           8

In [45]:
#calling out the salary column
salary=df_new["salary($)"]
salary

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [46]:
#fitting the data
reg=linear_model.LinearRegression()
reg.fit(new_df_h,salary)

LinearRegression()

In [47]:
#checking for their coeffient
reg.coef_

array([2813.00813008, 1333.33333333, 2926.82926829])

In [48]:
#checking for their intercept
reg.intercept_

11869.91869918695

In [49]:
#checking for their score
reg.score

<bound method RegressorMixin.score of LinearRegression()>

 Using this predict salaries for following candidates:
**2 yr experience, 9 test score, 6 interview score**

In [50]:
reg.predict([[2,9,6]])

array([47056.91056911])

Using this predict salaries for following candidates,
**12 yr experience, 10 test score, 10 interview score**


In [51]:
reg.predict([[12,10,10]])

array([88227.64227642])